- djangocassandra/db/backends/cassandra/base.py
- djangocassandra/db/backends/cassandra/cursor.py
- djangocassandra/db/backends/cassandra/introspection.py
- djangocassandra/db/backends/cassandra/schema.py
I made a CassandraCursor class that implements a lot of the same interface as the MySQLdb cursor class so that django can pass this object around and that our database backend can find this useful. This will make a lot of the database introspection and migration features that are apart of Django 1.7
I also noticed that Django 1.7 refactored a lot of the DatabaseWrapper functionality into methods that make sense. I already had this logically seperated in a similar way but I went ahead and refactored what I had into the new DatabaseWrapper interface methods.
> Cassandra Cursor

- djangocassandra/db/backends/cassandra/base.py
- djangocassandra/db/backends/cassandra/creation.py
- djangocassandra/db/backends/cassandra/cursor.py
- djangocassandra/db/models.py
- tests/models.py
- tests/settings.py
- tests/test_insertion.py
- tests/util.py
During refactoring the the last few revisions the existing test cases no longer passed. Some of this was due to bugs but mainly had to do with the wrong interface methods being called from the test utilities. This is all fixed now.
> Clean Up DatabaseWrapper And Fix Tests

- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/backends/cassandra/schema.py
- djangocassandra/db/fields.py
* I think the SchemaEditor is functional now at least for simple migrations across one db and without changing keyspaces.
* Added an AutoFieldUUID to djangocassandra.db.fields that handles UUID primary keys correctly. This should be used instead of Django's default AutoField class
> Fixing SchemaEditor and AutoFieldUUID

- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/backends/cassandra/exceptions.py
- djangocassandra/db/backends/cassandra/predicate.py
- djangocassandra/db/backends/cassandra/utils.py
- tests/settings.py
* Ported predicate.py module from https://github.com/vaterlaus/django_cassandra_backend to handle in memory sorting and filtering operations.
* Modified compiler.py to take advantage of predicate.py in retriving and filtering results.
* Modified settings.py to look for environment variables to configure your cassandra host and port (original defaults are still in place i.e localhost:9042)
> In Memory Operations (Relational Support)

- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/fields.py
- djangocassandra/db/models.py
- doc/source/usage.rst
- tests/models.py
- tests/test_insertion.py
- tests/test_queries.py
- tests/test_related.py
* Wrote tests to exercise Django ForeignKey creation and queries.
* Refactored AutoFieldUUID auto value creation into a method on the field class called "get_auto_value"
* In the case that the default Django AutoField is being used the database backend now counts the current rows in the column family and then sets the new insert. Auto-incrementing integer fields really only work on single node Cassandra clusters or clusters that replecate data across all nodes before responding not to mention counting the rows is expensive and not scalable. I pretty much just added this for compatibility, there could be a more efficient way to implement this.
* In all other cases the database backend looks for the "get_auto_value" method to be defined on the custom auto field.
* Updated "Usage" …
> Foreign Keys

- djangocassandra/db/models.py
- setup.py
Map, Set and List columns need extra parameters (key_type, value_type). I just make all key_types 'columns.Text' since I'm not sure the best way to handle other types of keys in Django. value_type is determined by the item_field attributes on those field classes.
> Fix Creation Of Map, Set and List Fields

- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/backends/cassandra/predicate.py
- djangocassandra/db/fields.py
There was an error in how the backend determines wether or not a range query can be evaluated efficiently by Cassandra. It was allowing attempts of efficent filtering on non-clustering columns.
> Fix Inefficent Range Filtering Error

- doc/source/index.rst
Simple typo on the spelling of Cassandra
> Changing the spelling on index.rst

- djangocassandra/db/fields.py
- setup.py
- tests/test_related.py
Modified the AutoUUIDField class to_python method to convert the UUID field to a string representation when adding it to the class.
> AutoUUID Field Should Be Represented As String

- .travis.yml
- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/backends/cassandra/predicate.py
- djangocassandra/db/fields.py
- djangocassandra/db/models.py
- djangocassandra/db/query.py
- setup.py
- tests/models.py
- tests/test_queries.py
- tests/util.py
Unfortunately this feature will not work out of the box. It will require your django models to inherit from djangocassandra.db.models.ColumnFamilyModel which has a custom manager/queryset which has the paging method attached to it (model.objects.next())
* Impelemented a ColumnFamilyModel class that your cassandra Models should inherit from.
* Impelemented a QuerySet method (djangocassandra.db.query.QuerySet) which has a pagination method called next()
* Implemented a ColumnFamilyModelManager class that utilizes the pagination enabled QuerySet
* Fixed a bug in the database backend compiler.py where query limit statement was not being applied.
> [Deliver #106712166] - Paging Functionality

- deploy.sh
- djangocassandra/db/backends/cassandra/compiler.py
- setup.py
- tests/test_queries.py
Nasty bug here where for inefficient queries the limit on the query wasn't being reset. Somewhere in the get/filter django sets a limit to 21 (I think this is MAX_GET_RESULTS +1; use grep to find if curious). When there were more than 21 results in the query set there was a good chance that the result that matches the provided filter would not be in the result set.
> Inefficent Queries (get/filter) Don't Return Results In Some Cases

- djangocassandra/db/fields.py
- setup.py
- tests/test_columnfamily.py
I didn't implement the value_to_string method for TokenPartitionKeyField which was causing an exception to be thrown on object serialization. That method now returns the values contained in the PK wrapped in the string "token()".
> Fix Serialization Of TokenPartitionKeyField

- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/backends/cassandra/predicate.py
- setup.py
- tests/models.py
- tests/test_columnfamily.py
- tests/test_queries.py
get() calls we not returning results in a case where the result you wanted was more that 21 rows deep due to a bug in the way result slices were applied. Implemented a fix and a unit test to cover the fixed case.
> Fix Results Not Being Returned For Inefficient Queries

- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/backends/cassandra/exceptions.py
- djangocassandra/db/backends/cassandra/predicate.py
- djangocassandra/db/meta.py
- setup.py
- tests/models.py
- tests/test_queries.py
* Added support for defining compound partition keys. define partition_keys member in Cassandra options class on your model definition.
* The classname for Cassandra options was not consistent. changed all instances of 'CassandraMeta' to 'Cassandra'
> Compound Partition Keys

- djangocassandra/db/meta.py
- setup.py
- tests/models.py
- tests/test_queries.py
* The way django passes models to the backend seems to be different than how I'm invoking it in the tests. I added some special model fetching code to make sure we're getting the class as defined including the "Cassandra" options class that holds the definition for partition and clustering keys.
> Fixed Cassandra Options Having No Effect

- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/fields.py
- setup.py
* Made allow_inefficient flag to be set in the model Cassandra sub class or as a setting in the database configuration in settings.py.
* Improved AutoFieldUUID to auto populate even if it isn't a primary key by setting a default default value function to uuid.uuid4.
> Configurable Allow Inefficient and Improved AutoFieldUUID

- djangocassandra/db/meta.py
- setup.py
* I wasn't setting the keyspace on the cqlengine model which was breaking generating the query in some cases.
> Set Keyspace on CQLEngine Model

- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/meta.py
- setup.py
- tests/models.py
- tests/test_columnfamily.py
* Fixed foreign key relations not being created correctly on the cqlengine side.
* Fixed order_by not correctly detecting when ForeginKey partition key fields were properly filtered for the query.
> Foreign Key Fields Not Created Properly In Meta Class

- djangocassandra/db/backends/cassandra/introspection.py
- setup.py
There are cases (when running tests) where Django calls table_names without passing a cursor object. Default is now None.
> Introspection table_names method needs default param.

- djangocassandra/db/backends/cassandra/base.py
- setup.py
- tests/test_operations.py
* Running Django tests requires support for the sqlflush management command. It returns an array of CQL commands to be executed against the server. The first statement is a use statement for the keyspace for the current connection and the rest are TRUNCATE statements for each table passed in.
> Sqlflush Management Command Support

- djangocassandra/db/backends/cassandra/cursor.py
- setup.py
* Cursor.execute method was throwing exceptions for queries that do not return results. I modified the check for _with_rows to handle None results.
> Fix Cursor Execute

- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/backends/cassandra/exceptions.py
- setup.py
* EmptyResultSet exception gets bubbled up when the django test suite does a in lookup with no values causing tests to fail.
> Handle EmptyResultSet Exception

- djangocassandra/db/fields.py
- setup.py
* Serializing tokens with UUID values was broken. Wrapped value in a str() call to prevent this.
> Fix Token Field Serialization

- djangocassandra/db/backends/cassandra/base.py
- setup.py
- tests/models.py
- tests/test_columnfamily.py
* DictFields were not returning an appropriate value for our database backend. The backend expects a python dict but it was being converted into an array of tuples. I modified the to_database method to leave the value as is in this case.
* Created a unit test to cover this.
> Fix DictField Support

- djangocassandra/db/meta.py
- setup.py
* Model meta class was using the passed in model instead of looking up the model registered with Django. I don't know what voodoo happens here but the passed in model does not have all the information required to properly render out the schema.
> Fix Model Meta Class __new__

- .gitignore
- djangocassandra/db/backends/cassandra/base.py
- djangocassandra/db/backends/cassandra/creation.py
- djangocassandra/db/backends/cassandra/predicate.py
- djangocassandra/db/backends/cassandra/schema.py
- djangocassandra/db/meta.py
- setup.py
- tests/test_queries.py
- tests/util.py
* Had to make some minor changes to support the new cqlengine api changes but now the backend supports Cassandra 3.x series.
* Incremented version to 0.6.0
* Reverted Django Date field to just use DateTime in cassandra to preserve backwards compatibility with Cassandra 2.x series.
* Added .py/ virtual environment directory to .gitignore.
> Upgrade to Cassandra Driver 3.7.0

- djangocassandra/db/backends/cassandra/cursor.py
- djangocassandra/db/backends/cassandra/introspection.py
- setup.py
- tests/test_introspection.py
* Cassandra 3.x series stores database schema metadata in the keyspace system_schema instead of schema. They also changed some field names so I wrote some compatibility code.
* Wrote some compatibility code in cassandra cursor to handle a returned ResultSet instead of an array/dict
* Wrote a unit test to cover get_table_list.
* Incremented version to 0.6.1 since this hotfix is to be published immediately.
> Fix get_table_list in DatabaseIntrospection to Fix Migrations

- djangocassandra/db/backends/cassandra/compiler.py
- setup.py
- tests/test_insertion.py
The delete method was only filtering on the instance's partition keys but not the clustering keys causing models with matching partition keys to run into MultipleRows exceptions in Cassandra while deleting.
* Fixed it so the delete method in the complier usins partition and clustering keys while generating the query.
> Fix Delete For Rows With Matching Partition Keys

- djangocassandra/db/models.py
- setup.py
* Data only gets denormalized to denormalized_models on create() I changed it so it happens on save() so that the models stay consistent through their lifetime. (This still respects should_denormalize).
* Made it so delete() calls make the "should_denormalize" check to give the user more control over deletion behavior.
> Denormalize on Save Instead of on Create

- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/backends/cassandra/predicate.py
- djangocassandra/db/fields.py
- djangocassandra/db/models.py
- setup.py
- tests/models.py
- tests/test_denormalization.py
* Deletion depends on more robust primary key support. We were running into issues where unexpected rows were being deleted. This was caused by django matching just one field of the primary key (the one defined as primary_key=True). I implemented a new PrimaryKey field to handle this correctly. Calling .pk on a model now returns a PrimaryKeyValue object which is an OrderedDict subclass containing the key/values of the partition keys and the clustering keys.
* Modified denormalization tests to catch the above unexpected deletion issue.
* Added a new DateTimeField that truncates the nanoseconds off of date time since Cassandra doesn't support nanoseconds.
* Updated version string to minor revision 0.7.0
> Primary Key Support (To Fix Deletion)

- djangocassandra/db/models.py
- setup.py
* Fixed an infinite recursion where attemption to get the PK when a ForeignKey is part of the keys by getting the value instead of going throug Django ForeignKey __get__ logic repeatedly.
> Fix Infinite Recursion When ForeignKey is part of Primary Key

- djangocassandra/db/fields.py
- djangocassandra/db/models.py
- djangocassandra/db/values.py
- setup.py
- tests/models.py
- tests/test_columnfamily.py
- tests/test_queries.py
* Fixed ColumnFamilyModel._get_pk_val to handle ForeignKey valued properly.
* Fixed PrimaryKeyField get_prep_value to handle ForeignKeys properly.
* Fixed FieldUUID and AutoFieldUUID get_prep_value methods to behave properly convert UUID values (and avoid trying to convert them to int).
* Fixed DateTimeField get_prep_value to always use 3 most significant digits.
* Modified unit tests to catch these edge cases.
* Refactored PrimaryKeyValue to values module since both fields and models modules require it.
* Incremented patch version to 0.7.4
> Primary Key Fixes

- .travis.yml
- djangocassandra/db/backends/cassandra/schema.py
- setup.py
- tests/models.py
- tests/test_command.py
* Altering a dict field failed on migration since the _add_field method on the Schama class doesn't know how to create Map columns. This has been fixed.
* Added a unit test for testing django migration features.
> Fix Migrations for DictField

- djangocassandra/db/backends/cassandra/schema.py
- setup.py
* removing or altering attributes on fields isn't well supported by the python cassandra-driver. I'm removing this functionality now since it's busted and most alters only effect Django side validation anyway.
> Don't Try To Remove or Alter Fields

- djangocassandra/db/backends/cassandra/schema.py
- setup.py
* sync_table tries to recreate old secondary indexes when adding a new field. I fixed it so all old columns are set to index=False before syncing.
> Ignore Old Indexed Fields When Adding New Field

- djangocassandra/db/backends/cassandra/schema.py
- setup.py
* Add field was calling keys() method on uninstantiated column_family instance. Changed it to call keys on ._columns instead.
> Fix Error in Add Field Method

- .gitignore
- .travis.yml
- djangocassandra/db/backends/cassandra/introspection.py
- djangocassandra/db/backends/cassandra/schema.py
- setup.py
- tests/test_introspection.py
* Fixed imports where the underlying modules have been moved in Django.
* get_table_list introspection now uses new TableInfo class to generate table metadata.
* Breaks Django <=1.7 support.
> Support Django 1.8
