Knotis/djangocassandra

- djangocassandra/db/backends/cassandra/schema.py
Implemented the required methods for doing schema migrations using cqlengine.
> Schema Editor

- djangocassandra/db/backends/cassandra/base.py
- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/backends/cassandra/creation.py
- djangocassandra/db/backends/cassandra/predicate.py
- djangocassandra/db/backends/cassandra/schema.py
- djangocassandra/db/models.py
- setup.py
- tests/util.py
* Changed references to cqlengine to cassandra.cqlengine
* Removed cqlengine from setup.py dependencies.
* Added requirement for Django < 1.8
> Remove CQLEngine Package

- setup.py
* Incremented version number to 0.0.3 (alpha release)
* Removed djangotoolbox from setup.py
* Added a note in the description to use djangotoolbox from https://github.com/kavdev/djangotoolbox/tree/patch-1
> Increment Version Number

- README.md
- doc/source/prerequisites.rst
- doc/source/quickstart.rst
* Fixed some hyperlink errors in the documentation.
* Updated README.md to refer users to https://djangocassandra.readthedocs.org
> Updating Readme and Documentation

- setup.py
* Incremented to version 0.0.4.
* Added blist to install_requires.
* Updated long_description to include a link to the documentation.
> Deploy PyPi

- .travis.yml
- README.md
I mostly just felt like doing this to see how difficult it was. To add coveralls support, all you need to do is go to Coveralls.io and auth github to do it.
> Added Coveralls and badges.

- wercker.yml
* Added wercker.yml config for wercker.com
> Add Werker Config

- doc/source/index.rst
Added a attribution to the quote on index.rst.
> Updated Documentation

- djangocassandra/db/backends/cassandra/base.py
- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/backends/cassandra/predicate.py
- djangocassandra/db/backends/cassandra/schema.py
- djangocassandra/db/models.py
- setup.py
* Implemented Update call that I managed to get this far without running into yet. Seems to work good now.
* Fixed some issues with add/remove fields in the SchemaEditor class. The column family class wasn't getting all of it's fields updated. I should probably be using the metaclass to generate a new class that has the appropriate values but this workaround of assiging the columns attribute directly seems to work fine.
* Enabled allow filtering by default on queries. I should add an option for this.
* Added a attribution to the quote on index.rst.
* Bumped Version to 0.1.0
* Fixed a bug that was preventing filtering on ForeignKey columns
> Release Version 0.1.0 Beta

- .travis.yml
> Updated travis yaml file.

- setup.py
> Incremented Version Number For 0.1.2 Beta Release

- djangocassandra/db/backends/cassandra/base.py
- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/backends/cassandra/creation.py
- djangocassandra/db/backends/cassandra/schema.py
- djangocassandra/db/exception.py
- djangocassandra/db/models.py
- tests/test_queries.py
- tests/util.py
Not perfect, but it'll cause a fewer stack traces.
Also, I removed pep8 errors in files I modified.
> Refactored create_keyspace into create_model.

- setup.py
And a whitespace removal because my vim is cool.
> Updated version number.

- djangocassandra/db/backends/cassandra/compiler.py
Increased query limit to 1000000 by default.
> Increased Limit On Queries

- djangocassandra/db/backends/cassandra/compiler.py
- setup.py
* Set the hardcoded 20 second timeout to None (no software timeout set)
> [Deliver #103625820] - Set Timeout to None

- deploy.sh
- setup.py
> Removing accidentally uploaded file.

- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/meta.py
- setup.py
There where a couple issues in the get_column_family method that were making column famlies not getting created with the appropriate partition/clustering keys.
> Fix Primary Key Creation

- djangocassandra/db/backends/cassandra/base.py
- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/backends/cassandra/predicate.py
- setup.py
* Paging now happens automagically behind the scenes in the backend using generators.
* Removed default limit statement from the backend.
* Made backend paging fetch_size configurable per-model in the Cassandra meta options class.
> Automatic Paging

- djangocassandra/db/backends/cassandra/compiler.py
- setup.py
* Accidentally removed all calls to ensure_connection during refactor causing database connection not to aquire.
> Make Sure Ensure Connection Is Called

- djangocassandra/db/backends/cassandra/compiler.py
- setup.py
The new count method wasn't correctly calculating the length of new style of results.
> Fix Count Method

- djangocassandra/db/backends/cassandra/base.py
- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/models.py
- setup.py
- tests/models.py
- tests/settings.py
- tests/test_connection.py
- tests/test_denormalization.py
- tests/test_operations.py
* Added denormalization features to ColumnFamilyManager class. To take advantage of denormalization on create use ColumnFamily manager as objects member on your ColumnFamilyModel (see test_denormalization.py)
> Denormalization Management

- djangocassandra/db/backends/cassandra/compiler.py
- djangocassandra/db/models.py
- setup.py
- tests/test_queries.py
- tests/test_related.py
* I was passing when I should have been continuing causing a variable used before deffinition error.
* Added some unit test just for fun.
> Fix Denormalize Method On ColumnFamilyModel

- djangocassandra/db/backends/cassandra/predicate.py
- djangocassandra/db/fields.py
- djangocassandra/db/query.py
- setup.py
* Pagination using tokens wasn't handling compound partition/clustering keys correctly.
> Fix Token Queries For Compound Partition Keys

- djangocassandra/db/backends/cassandra/base.py
- djangocassandra/db/backends/cassandra/creation.py
- djangocassandra/db/backends/cassandra/schema.py
- setup.py
* Refactored some logic, there where two different cases for creating db tables with duplicated logic. I unified these paths.
* Ensure that keyspace is set before model creation.
> Fix Issues with Migrations

- djangocassandra/db/backends/cassandra/base.py
- setup.py
- tests/models.py
- tests/test_insertion.py
- tests/test_related.py
- Wrapping connection creation in a try/catch and only creating a new connection if one does not already exist.
- Added some unit tests to cover deleting models related by a foreign key.
> Fix Memory Leak

- djangocassandra/db/models.py
- setup.py
- tests/models.py
- tests/test_denormalization.py
* Now when you delete a model that has been denormalized it will also delete all denormalized instances.
* Added to the test_denormalization unit test to cover this.
* Incremented patch version.
> Denormalized Deletion

- djangocassandra/db/fields.py
- setup.py
* get_internal_type was returning 'PrimaryKeyField', now it correctly returns the get_internal_type method of the field it's wrapping.
> Fix PrimaryKeyField get_internal_type Method

- djangocassandra/db/fields.py
- setup.py
- tests/models.py
* Fixed an edge case where PrimaryKeyField returned the wrong internal_type for ForeignKeys.
> Fix PrimaryKeyField when ForeignKey is field_class.

- djangocassandra/db/fields.py
- setup.py
- tests/models.py
* Changed the way parameters are passed into the child field class to work better with makemigrations command.
> Fix PrimaryKeyField to Work With makemigrations

- djangocassandra/db/backends/cassandra/schema.py
- setup.py
* Altering a field works just like creating a model. Removed unecessary code and just called create_model now.
> Fix Schema Alter Field
